spring:
  application:
    name: system-events-service
  cloud:
    config:
      password: secret
      username: root
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev

server:
  port: 8086