spring:
  main:
    allow-bean-definition-overriding: true
  jackson:
    property-naming-strategy: SNAKE_CASE

token:
  private-key: projecthub.jks
  public-key: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtLJn43ZP4ioanDYkowv+4NNdcKkMMM+f+YsWof32ikWyW6gj5eMD0WQfpppXy4/d08DniZ6IcxEHbo679bNmw5+sP7S6AXWnRewbMjqNC9SkIGerPo4X8CovNXPkyC5lMvVn2m4Zbmrr49P1z4Tx465xtG87VaJ2b1/wqX+NFuChqZZNm+hNIxPOtlwsnxeAPBlWxvrEKfFXLal1L5qkfKHIeih/XfCa+B1gB9LmlxBjNl6qWd++zypzL+XPJPJFyfCJAi6QhemzYArIcoueWiqmi+tfz8NohbhOXoXuMAn5taYnpNAlZcOFn4DAsu1eN22oHqzt4uYPmeUMmTU5bwIDAQAB-----END PUBLIC KEY-----
  password: projecthub
  alias: projecthub
  length: 12
  duration:
    token:
      activation: 1800
      reset: 1800

eureka:
  instance:
    prefer-ip-address: true
    metadata-map:
      zone: zone1
  client:
    prefer-same-zone-eureka: true
    register-with-eureka: true
    fetch-registry: true
    region: region1
    service-url:
      zone1: http://discovery-server:8761/eureka/
    availability-zones:
      region1: zone1

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
