spring:
  application:
    name: task-service
  cloud:
    config:
      password: secret
      username: root
      enabled: true
      uri: ${CONFIG_SERVER_URL}
  config:
    import: "optional:configserver:"
  profiles:
    active: dev
  jpa:
    properties:
      hibernate:
        session_factory:
          interceptor: ba.unsa.etf.nwt.taskservice.utility.HibernateUtils
  rabbitmq:
    host: localhost
    password: password
    username: projecthub

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8083
