spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task-service-dev
    username: projecthub
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5432/task-service-dev
    user: projecthub
    password: password