spring:
  datasource:
    url: ${DATABASE_URL}
    username: projecthub
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: ${DATABASE_URL}
    user: projecthub
    password: password
  mail:
    host: in-v3.mailjet.com
    port: 587
    username: f0daf554447d64120067f6f8d9c1a2bd
    password: 123658e6526109f8c5116167ff204819

mail:
  from: atlantic.project.hub@gmail.com
