spring:
  application:
    name: email-service
  cloud:
    config:
      password: secret
      username: root
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  rabbitmq:
    host: localhost
    password: password
    username: projecthub

server:
  port: 8085
